---
- name: Change APT sources.list
  ansible.builtin.template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    mode: '644'

- name: Config debian.sources
  ansible.builtin.deb822_repository:
    name: debian
    uris: https://mirrors.tuna.tsinghua.edu.cn/debian
    suites:
      - '{{ ansible_distribution_release }}'
      - '{{ ansible_distribution_release }}-updates'
    components:
      - main
      - contrib
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: present

- name: Config security.sources
  ansible.builtin.deb822_repository:
    name: security
    uris: https://security.debian.org/debian-security
    suites: '{{ ansible_distribution_release }}-security'
    components:
      - main
      - contrib
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: present

- name: Config proxy for apt
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/80proxy
    content: |
      Acquire::http::proxy::mirrors.tuna.tsinghua.edu.cn "DIRECT";
      Acquire::http::proxy "{{ base_proxy_env.http_proxy }}";
      Acquire::https::proxy "{{ base_proxy_env.http_proxy }}";
    mode: '644'
  when:
    - base_proxy_env.http_proxy is defined
    - base_proxy_env.http_proxy != ""

- name: Reomove proxy config for apt
  ansible.builtin.file:
    dest: /etc/apt/apt.conf.d/80proxy
    state: absent
  when:
    - not base_proxy_env
