---
- name: Change APT sources.list
  ansible.builtin.template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    mode: "644"

- name: Config debian.sources
  ansible.builtin.deb822_repository:
    name: debian
    uris: "{{ base_apt_mirrors[base_mirror_region] | default(apt_mirrors['default']) }}/{{ ansible_facts['distribution'] | lower }}"
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
      - "{{ ansible_facts['distribution_release'] }}-updates"
    components:
      - main
      - contrib
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: present

- name: Config security.sources
  ansible.builtin.deb822_repository:
    name: security
    uris: https://security.debian.org/debian-security
    suites: "{{ ansible_facts['distribution_release'] }}-security"
    components:
      - main
      - contrib
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: present

- name: Config proxy for apt
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/80proxy
    content: |
      Acquire::http::proxy::mirrors.tuna.tsinghua.edu.cn "DIRECT";
      Acquire::http::proxy "{{ base_proxy_env.http_proxy }}";
      Acquire::https::proxy "{{ base_proxy_env.http_proxy }}";
    mode: "644"
  when:
    - base_proxy_env.http_proxy is defined
    - base_proxy_env.http_proxy != ""

- name: Reomove proxy config for apt
  ansible.builtin.file:
    dest: /etc/apt/apt.conf.d/80proxy
    state: absent
  when:
    - not base_proxy_env

# https://wiki.debian.org/UnattendedUpgrades
# To aid debugging you may need to run unattended-upgrades manually thus:
# sudo unattended-upgrade -d
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Set auto upgrades
  ansible.builtin.template:
    src: etc/apt/apt.conf.d/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "644"
    owner: root
    group: root

- name: Set unattended-upgrades
  ansible.builtin.template:
    src: etc/apt/apt.conf.d/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "644"
    owner: root
    group: root


